service: serverless-task-8

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: GET
          path: /api/profile
      - http:
          method: GET
          path: /ping