export const ConstantsRepository = {
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  CARTS_REPOSITORY: 'CARTS_REPOSITORY',
  CART_ITEMS_REPOSITORY: 'CART_ITEMS_REPOSITORY',
  PRODUCTS_REPOSITORY: 'PRODUCTS_REPOSITORY',
};

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
